### ISSUE TITLE
Cannot run in Ubuntu 20.04 with ruby 2.7.0p0

### ISSUE THREAD

**Issue by jaredbarez** [Acceis/bqm#10]
`$ ruby bin/bqm -l`
`[+] Available datasets:`
`Traceback (most recent call last):`
`	1: from bin/bqm:84:in <main>`
`bin/bqm:62:in get_datasets: undefined method load_file for JSON:Module (NoMethodError)`
`$`
`$ ruby --version`
`ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]`
`$`

**Comment by noraj** [comment]
Should be fixed in v1.2.0 cf. f2bfee5b020d4f666fa168a4403ca644c690b777
