### ISSUE TITLE
Add support for local files in query-sets.json

### ISSUE THREAD

**Issue by gbe** [Acceis/bqm#23]
Hello,

as discussed in https://github.com/ThePorgs/Exegol-images/pull/163, could you add support so that the tool can import local files and not just remote ones?

Thanks in advance

**Comment by noraj** [comment]
I added the option to merge local custom queries files from the CLI rather than adding support for local files in the dataset (`query-sets.json`).

https://github.com/Acceis/bqm/releases/tag/v1.4.0
