### ISSUE TITLE
Commandline wishes

### ISSUE THREAD

**Issue by gbe** [Acceis/bqm#25]
Hello @noraj,

thank you for the version 1.4.0 of bqm as we can now merge local files \o/. Well done.

I have some suggestions/whishes in order to address https://github.com/ThePorgs/Exegol-images/pull/163

1/ When starting the Exegol container, we only need to manipulate local files (Exegol's and the user's) and the version 1.4.0 pulls remote files by default. This means that implementing the PR in the current state of bqm still implies to empty temporarily the file query-sets.json as a workaround to disable remote sources. Something we agreed is not a good idea.

Hence my whish: could you add a CLI option to disable the pulling of remote sources ?

2/ Still for the same Exegol PR, rather than setting local files with `-i /tmp/a.json,/tmp/b.json`, could you support either:
- `-i /tmp/directory -i /tmp/a.json -i /tmp/b.json`
- or `-d /tmp/directory -i /tmp/a.json -i /tmp/b.json`

This would add support for directories. Bqm could autodetect the .json files in the folders. 
In the first case, the folder is included with the argument `-i` (as of version 1.4.0), second case with a new argument `-d`. I don't know what you may prefer, these are suggestions, my favorite is the one with `-d`.

Having an option to include directories means that in Exegol, we would not need to have a wrapper around bqm to detect the files from a folder and dynamically construct the argument to pass to bqm.
Plus, in both cases, I found the comma separator to break bqm if the user's file contains the character `,`. This is why I suggest to have support for multiple -d and -i arguments.

3/ To expand a bit my thoughts above the above 1/, I think that bqm could be started a bit differently.

Rather than pulling remote sources by default and optionnally merge them with local files, bqm could start as an empty shell.
Then, the sources are enabled one by one on command-line:
- `-r [data-sets.json]`: to pull the remote sources for the `optional` file data-sets.json. If the switch is set and without a file, then the default dataset file is chosen. I think it may intereset users to set their own data-sets file if they want custom remote sources (for example: a remote file on an intranet).
- `-d <directory>`: to include one local set directory.
- `-i <file>`: to include one local set file.

All three switches could be set several times, as there could be several remote sources, several directories, and several individual files.

Best

**Comment by noraj** [comment]
I'll open separate issue and answer there. There is too much stuff for one issue.
