### ISSUE TITLE
disable remote file pulling

### ISSUE THREAD

**Issue by noraj** [Acceis/bqm#26]
Asked by @gbe in #25

> 1/ When starting the Exegol container, we only need to manipulate local files (Exegol's and the user's) and the version 1.4.0 pulls remote files by default. This means that implementing the PR in the current state of bqm still implies to empty temporarily the file query-sets.json as a workaround to disable remote sources. Something we agreed is not a good idea.
> 
> Hence my whish: could you add a CLI option to disable the pulling of remote sources ?

**Comment by noraj** [comment]
It would be easy to do that, but I don't understand why it's an issue to pull remote resources, I mean several tools included in Exegol may do that?

**Comment by gbe** [comment]
Hi @noraj,

thanks for taking the time to answer my points.

I see several reasons to not pull remote resources when starting an Exegol container:
- If the server where the resource is hosted is unresponsive, it may hang the container start
- Some remote resources may not interest the end users
- In the case of Exegol, not pulling remote resources creates the opportunity to replace entirely the file provided by Exegol. It's actually what led me to create the Exegol's PR in the first place, then it was suggested to also support the merging feature.
- but most of all, when doing an engagement at the customer's premises, the auditor may not have internet access as it may require an authentication against the customer's proxy.

For all these reasons, I see a need for your tool to offer the possibiliy to work offline :)

**Comment by noraj** [comment]
> If the server where the resource is hosted is unresponsive, it may hang the container start

Why? Remote resources are fetched at runtime. And even if the test commands are issued when the container starts, the test command for bqm in Exegol is `bqm --help` which doesn't interact online. So I don't see how bqm could delay the container start. However it's true that an unavailable remote resource prevent to use the tool locally if this is not possible to disable it.

> Some remote resources may not interest the end users

True, I'll add an option anyway.

> In the case of Exegol, not pulling remote resources creates the opportunity to replace entirely the file provided by Exegol. It's actually what led me to create the Exegol's PR in the first place, then it was suggested to also support the merging feature.

I'm not sure to understand what you mean here.

> but most of all, when doing an engagement at the customer's premises, the auditor may not have internet access as it may require an authentication against the customer's proxy.

True, offline use.

**Comment by gbe** [comment]
Just to clarify the part you did not understand, it means that I could use your tool with Exegol to merge local files, and not necessarily with the customqueries.json file provided by Exegol.
It is not directly your concern, it was just to give you some context.

**Comment by Dramelac** [comment]
> > If the server where the resource is hosted is unresponsive, it may hang the container start
> 
> Why? Remote resources are fetched at runtime. And even if the test commands are issued when the container starts, the test command for bqm in Exegol is `bqm --help` which doesn't interact online. So I don't see how bqm could delay the container start. However it's true that an unavailable remote resource prevent to use the tool locally if this is not possible to disable it.
>

To add some context, @gbe try to integrate bqm into the `my-resources` feature to allow end user of exegol to customize personnaly their own query etc.

This feature is executed when the container is created by the wrapper (not at build time). It will **not** hang the container start because it's a 'background' task in the container **however** it would hang the starting of background service like OpenVPN (because we are waiting for my-resource to finish before running the VPN profile to avoid any conflict).
