### ISSUE TITLE
Argument duplicate support and local directory support

### ISSUE THREAD

**Issue by noraj** [Acceis/bqm#27]
Asked by @gbe in https://github.com/Acceis/bqm/issues/25

> 2/ Still for the same Exegol PR, rather than setting local files with `-i /tmp/a.json,/tmp/b.json`, could you support either:
> 
>     * `-i /tmp/directory -i /tmp/a.json -i /tmp/b.json`
> 
>     * or `-d /tmp/directory -i /tmp/a.json -i /tmp/b.json`
> 
> 
> This would add support for directories. Bqm could autodetect the .json files in the folders. In the first case, the folder is included with the argument `-i` (as of version 1.4.0), second case with a new argument `-d`. I don't know what you may prefer, these are suggestions, my favorite is the one with `-d`.
> 
> Having an option to include directories means that in Exegol, we would not need to have a wrapper around bqm to detect the files from a folder and dynamically construct the argument to pass to bqm. Plus, in both cases, I found the comma separator to break bqm if the user's file contains the character `,`. This is why I suggest to have support for multiple -d and -i arguments.

**Comment by noraj** [comment]
There are 2 things here. 

The first thing, is to have `-i /tmp/a.json -i /tmp/b.json` instead of `-i /tmp/a.json,/tmp/b.json` this is a no because it's a limitation of OptionParser. I would have preferred support for duplicate arguments or even elements separated by a space `-i /tmp/a.json /tmp/b.json` rather than a comma but it's not possible with OptionParser and I don't want to use an external dependency just for that. Also I don't think having a comma in a bloodhound query file name is a real life issue.

The second thing is to be able to handle folders. There is no need to have `-d` I can detect if the input is a file or a directory and handle that automatically so this can be supported in `-i`. I would assume that is a directory is passed then all json files in this directory must be bloodhound queries. Also if it's possible to load many files from a directory having support for duplicate arguments is useless.

**Comment by gbe** [comment]
> The first thing, is to have -i /tmp/a.json -i /tmp/b.json instead of -i /tmp/a.json,/tmp/b.json this is a no because it's a limitation of OptionParser. I would have preferred support for duplicate arguments or even elements separated by a space -i /tmp/a.json /tmp/b.json rather than a comma but it's not possible with OptionParser and I don't want to use an external dependency just for that. Also I don't think having a comma in a bloodhound query file name is a real life issue.

Ok, I understand the limitation about OptionParser and your choice to not use an external dependency.

> The second thing is to be able to handle folders. There is no need to have -d I can detect if the input is a file or a directory and handle that automatically so this can be supported in -i. I would assume that is a directory is passed then all json files in this directory must be bloodhound queries.

It's great then if you can detect if the input is a file or a directory.
Assuming that all json files from a directory are bloodhound queries is acceptable in my opinion. Just bear in mind that the folder may contain other files like a README.md.

> Also if it's possible to load many files from a directory having support for duplicate arguments is useless.

Well, you never know, a user may have different folders for many reasons. At least, you still give the choice to the user with the following command: `bqm -o /tmp/out.json -i /tmp/folder1/,/tmp/folder2/,/tmp/file.json`

Thanks for your help
