### ISSUE TITLE
Compass security repos broken.

### ISSUE THREAD

**Issue by kain0x** [Acceis/bqm#8]
The compass security repository is broken into **data/query-sets.json.**

`https://raw.githubusercontent.com/CompassSecurity/BloodHoundQueries/master/customqueries.json`
need to be replaced by :
`https://raw.githubusercontent.com/CompassSecurity/BloodHoundQueries/master/BloodHound_Custom_Queries/customqueries.json
`

**Comment by noraj** [comment]
Thanks. Seems upstream created a folder one month ago.
